"""
Unified ERP Target System: ALERP (Army Logistics Enterprise Resource Planning)

Consolidated schema that merges capabilities from both GCSS-Army (System Alpha)
and LMP (System Bravo) into a single, modernized data model.

Key design changes vs. legacy systems:
- Modern, readable field naming (no SAP abbreviations)
- UUID-based primary keys
- Consistent date/time formats with timezone
- Normalized reference data
- Built-in audit columns on every table
- Standardized status enumerations
"""

SYSTEM_NAME = "ALERP"
SYSTEM_DESCRIPTION = (
    "Army Logistics Enterprise Resource Planning - A unified logistics management "
    "system consolidating equipment readiness, supply chain, procurement, and "
    "distribution operations into a single authoritative platform."
)

SCHEMAS = {
    "assets": {
        "description": "Unified Asset Registry - All equipment, vehicles, weapons systems, and C4ISR assets",
        "table_name": "assets",
        "source_tables": ["GCSS-Army.EQUI_MASTER"],
        "fields": [
            {"name": "asset_id", "type": "UUID", "description": "Unique asset identifier", "example": "a1b2c3d4-e5f6-7890-abcd-ef1234567890"},
            {"name": "legacy_system", "type": "VARCHAR(20)", "description": "Originating legacy system", "example": "GCSS_ARMY"},
            {"name": "legacy_id", "type": "VARCHAR(30)", "description": "Original system identifier", "example": "000000000010045231"},
            {"name": "nsn", "type": "VARCHAR(13)", "description": "National Stock Number", "example": "2350-01-087-1095"},
            {"name": "lin", "type": "VARCHAR(10)", "description": "Line Item Number", "example": "M77A2B"},
            {"name": "nomenclature", "type": "VARCHAR(100)", "description": "Standard nomenclature", "example": "TANK, COMBAT, FULL TRACKED, 120MM GUN, M1A2 SEP V3"},
            {"name": "short_name", "type": "VARCHAR(50)", "description": "Common name", "example": "M1A2 ABRAMS"},
            {"name": "asset_category", "type": "VARCHAR(30)", "description": "Asset category enum", "example": "TRACKED_VEHICLE"},
            {"name": "serial_number", "type": "VARCHAR(30)", "description": "Manufacturer serial number", "example": "GDLS-2019-4521"},
            {"name": "manufacturer", "type": "VARCHAR(80)", "description": "Manufacturer name", "example": "General Dynamics Land Systems"},
            {"name": "manufacturer_cage", "type": "VARCHAR(5)", "description": "Manufacturer CAGE code", "example": "1GDL5"},
            {"name": "acquisition_date", "type": "DATE", "description": "Date acquired", "example": "2018-11-20"},
            {"name": "acquisition_cost", "type": "DECIMAL(15,2)", "description": "Acquisition cost (USD)", "example": "6210000.00"},
            {"name": "fielding_date", "type": "DATE", "description": "Date fielded to unit", "example": "2019-03-15"},
            {"name": "owning_uic", "type": "VARCHAR(6)", "description": "Owning unit UIC", "example": "W45XAA"},
            {"name": "owning_unit_name", "type": "VARCHAR(80)", "description": "Unit designation", "example": "2D ABCT, 1ST ARMORED DIVISION"},
            {"name": "installation", "type": "VARCHAR(50)", "description": "Current installation", "example": "Fort Bliss"},
            {"name": "location_detail", "type": "VARCHAR(50)", "description": "Specific location on post", "example": "Motor Pool Alpha, Bldg 2401"},
            {"name": "readiness_status", "type": "VARCHAR(3)", "description": "Current readiness (FMC/PMC/NMC)", "example": "FMC"},
            {"name": "status_reason", "type": "VARCHAR(100)", "description": "Reason for current status", "example": ""},
            {"name": "created_at", "type": "TIMESTAMP WITH TIME ZONE", "description": "Record creation timestamp", "example": "2024-01-15T10:30:00Z"},
            {"name": "updated_at", "type": "TIMESTAMP WITH TIME ZONE", "description": "Last update timestamp", "example": "2024-01-15T14:22:00Z"},
            {"name": "updated_by", "type": "VARCHAR(50)", "description": "Last updated by (user principal)", "example": "sgt.johnson@army.mil"},
        ],
    },
    "maintenance_orders": {
        "description": "Unified Maintenance Work Orders - All corrective, preventive, and scheduled maintenance",
        "table_name": "maintenance_orders",
        "source_tables": ["GCSS-Army.AUFK_WORKORDER"],
        "fields": [
            {"name": "order_id", "type": "UUID", "description": "Unique order identifier", "example": "b2c3d4e5-f6a7-8901-bcde-f12345678901"},
            {"name": "legacy_system", "type": "VARCHAR(20)", "description": "Originating system", "example": "GCSS_ARMY"},
            {"name": "legacy_order_number", "type": "VARCHAR(20)", "description": "Original order number", "example": "000004521001"},
            {"name": "asset_id", "type": "UUID", "description": "FK to assets table", "example": "a1b2c3d4-e5f6-7890-abcd-ef1234567890"},
            {"name": "order_type", "type": "VARCHAR(20)", "description": "Type enum (SCHEDULED, UNSCHEDULED, ANNUAL_SERVICE, MODIFICATION)", "example": "SCHEDULED"},
            {"name": "title", "type": "VARCHAR(120)", "description": "Order title", "example": "Scheduled Maintenance - AGT-1500 Engine Overhaul"},
            {"name": "description", "type": "TEXT", "description": "Detailed description", "example": "Full engine overhaul per TM 9-2350-264-20..."},
            {"name": "priority", "type": "INTEGER", "description": "Priority (1=URGENT, 2=HIGH, 3=ROUTINE)", "example": "2"},
            {"name": "status", "type": "VARCHAR(20)", "description": "Status enum (CREATED, PLANNED, IN_PROGRESS, AWAITING_PARTS, COMPLETED, CANCELLED)", "example": "IN_PROGRESS"},
            {"name": "owning_uic", "type": "VARCHAR(6)", "description": "Responsible unit UIC", "example": "W45XAA"},
            {"name": "work_center", "type": "VARCHAR(50)", "description": "Performing work center", "example": "Maintenance Company A, 3rd Shop"},
            {"name": "scheduled_start", "type": "DATE", "description": "Planned start date", "example": "2024-02-01"},
            {"name": "scheduled_end", "type": "DATE", "description": "Planned end date", "example": "2024-02-15"},
            {"name": "actual_start", "type": "DATE", "description": "Actual start date", "example": "2024-02-01"},
            {"name": "actual_end", "type": "DATE", "description": "Actual end date", "example": None},
            {"name": "estimated_hours", "type": "DECIMAL(7,2)", "description": "Estimated man-hours", "example": "240.00"},
            {"name": "actual_hours", "type": "DECIMAL(7,2)", "description": "Actual man-hours logged", "example": "186.50"},
            {"name": "fault_code", "type": "VARCHAR(20)", "description": "Standardized fault code", "example": "ENG-0042"},
            {"name": "cost_center", "type": "VARCHAR(20)", "description": "Cost allocation center", "example": "CC-1AD-MAINT"},
            {"name": "created_at", "type": "TIMESTAMP WITH TIME ZONE", "description": "Record creation timestamp", "example": "2024-01-20T08:00:00Z"},
            {"name": "created_by", "type": "VARCHAR(50)", "description": "Created by", "example": "cw3.martinez@army.mil"},
            {"name": "updated_at", "type": "TIMESTAMP WITH TIME ZONE", "description": "Last update timestamp", "example": "2024-01-25T16:30:00Z"},
        ],
    },
    "supply_items": {
        "description": "Unified Supply Catalog - Consolidated materiel master from both systems",
        "table_name": "supply_items",
        "source_tables": ["GCSS-Army.MARA_SUPPLY", "LMP.WAREHOUSE_INVENTORY"],
        "fields": [
            {"name": "item_id", "type": "UUID", "description": "Unique item identifier", "example": "c3d4e5f6-a7b8-9012-cdef-123456789012"},
            {"name": "nsn", "type": "VARCHAR(13)", "description": "National Stock Number", "example": "2940-01-576-4108"},
            {"name": "nomenclature", "type": "VARCHAR(100)", "description": "Standard nomenclature", "example": "FILTER ASSEMBLY, OIL, ENGINE"},
            {"name": "short_description", "type": "VARCHAR(60)", "description": "Short description", "example": "Oil Filter - M1A2 AGT-1500"},
            {"name": "item_category", "type": "VARCHAR(30)", "description": "Category enum", "example": "REPAIR_PART"},
            {"name": "material_group", "type": "VARCHAR(30)", "description": "Material group", "example": "ENGINE_COMPONENTS"},
            {"name": "unit_of_measure", "type": "VARCHAR(10)", "description": "Standard UOM", "example": "EACH"},
            {"name": "weight_lbs", "type": "DECIMAL(11,3)", "description": "Unit weight in pounds", "example": "2.450"},
            {"name": "unit_cost", "type": "DECIMAL(11,2)", "description": "Standard unit cost (USD)", "example": "47.50"},
            {"name": "shelf_life_days", "type": "INTEGER", "description": "Shelf life in days (NULL=unlimited)", "example": "730"},
            {"name": "hazmat_class", "type": "VARCHAR(10)", "description": "Hazmat classification (NONE if N/A)", "example": "NONE"},
            {"name": "is_critical", "type": "BOOLEAN", "description": "Critical supply item flag", "example": "false"},
            {"name": "primary_vendor_id", "type": "UUID", "description": "FK to vendors table", "example": "d4e5f6a7-b8c9-0123-defa-234567890123"},
            {"name": "reorder_point", "type": "INTEGER", "description": "Reorder trigger quantity", "example": "50"},
            {"name": "safety_stock", "type": "INTEGER", "description": "Minimum safety stock", "example": "25"},
            {"name": "created_at", "type": "TIMESTAMP WITH TIME ZONE", "description": "Record creation timestamp", "example": "2024-01-10T12:00:00Z"},
            {"name": "updated_at", "type": "TIMESTAMP WITH TIME ZONE", "description": "Last update timestamp", "example": "2024-01-15T09:15:00Z"},
        ],
    },
    "vendors": {
        "description": "Unified Vendor Registry - All suppliers, manufacturers, and contractors",
        "table_name": "vendors",
        "source_tables": ["LMP.VENDOR_MASTER"],
        "fields": [
            {"name": "vendor_id", "type": "UUID", "description": "Unique vendor identifier", "example": "d4e5f6a7-b8c9-0123-defa-234567890123"},
            {"name": "legacy_system", "type": "VARCHAR(20)", "description": "Originating system", "example": "LMP"},
            {"name": "legacy_vendor_id", "type": "VARCHAR(20)", "description": "Original vendor ID", "example": "V-000054321"},
            {"name": "name", "type": "VARCHAR(120)", "description": "Vendor legal name", "example": "General Dynamics Land Systems LLC"},
            {"name": "division", "type": "VARCHAR(80)", "description": "Division/subsidiary", "example": "Combat Systems Division"},
            {"name": "cage_code", "type": "VARCHAR(5)", "description": "CAGE Code", "example": "1GDL5"},
            {"name": "duns_number", "type": "VARCHAR(13)", "description": "DUNS Number", "example": "0068244950000"},
            {"name": "sam_uei", "type": "VARCHAR(12)", "description": "SAM.gov Unique Entity ID", "example": "XXXXXXXXXX01"},
            {"name": "address_line1", "type": "VARCHAR(80)", "description": "Street address", "example": "38500 Mound Rd"},
            {"name": "city", "type": "VARCHAR(50)", "description": "City", "example": "Sterling Heights"},
            {"name": "state", "type": "VARCHAR(2)", "description": "State code", "example": "MI"},
            {"name": "zip_code", "type": "VARCHAR(10)", "description": "ZIP code", "example": "48310"},
            {"name": "country", "type": "VARCHAR(3)", "description": "Country code", "example": "US"},
            {"name": "vendor_type", "type": "VARCHAR(20)", "description": "Type enum (PRIME_CONTRACTOR, TIER1_SUBCONTRACTOR, SMALL_BUSINESS, etc.)", "example": "PRIME_CONTRACTOR"},
            {"name": "is_small_business", "type": "BOOLEAN", "description": "Small business flag", "example": "false"},
            {"name": "payment_terms", "type": "VARCHAR(20)", "description": "Standard payment terms", "example": "NET_30"},
            {"name": "is_active", "type": "BOOLEAN", "description": "Active vendor flag", "example": "true"},
            {"name": "created_at", "type": "TIMESTAMP WITH TIME ZONE", "description": "Record creation timestamp", "example": "2015-06-20T00:00:00Z"},
            {"name": "updated_at", "type": "TIMESTAMP WITH TIME ZONE", "description": "Last update timestamp", "example": "2024-01-08T11:30:00Z"},
        ],
    },
    "procurement_orders": {
        "description": "Unified Procurement Orders - Consolidated purchase orders and contracts",
        "table_name": "procurement_orders",
        "source_tables": ["LMP.PURCHASE_ORDERS", "LMP.PO_LINE_ITEMS"],
        "fields": [
            {"name": "order_id", "type": "UUID", "description": "Unique procurement order identifier", "example": "e5f6a7b8-c9d0-1234-efab-345678901234"},
            {"name": "legacy_system", "type": "VARCHAR(20)", "description": "Originating system", "example": "LMP"},
            {"name": "legacy_po_number", "type": "VARCHAR(20)", "description": "Original PO number", "example": "4500089231"},
            {"name": "order_type", "type": "VARCHAR(20)", "description": "Type enum (STANDARD, BLANKET, CONTRACT_CALL)", "example": "STANDARD"},
            {"name": "vendor_id", "type": "UUID", "description": "FK to vendors table", "example": "d4e5f6a7-b8c9-0123-defa-234567890123"},
            {"name": "contract_number", "type": "VARCHAR(30)", "description": "DoD contract reference", "example": "W56HZV-20-C-0045"},
            {"name": "total_value", "type": "DECIMAL(15,2)", "description": "Total order value (USD)", "example": "1245000.00"},
            {"name": "order_date", "type": "DATE", "description": "Order creation date", "example": "2024-01-08"},
            {"name": "required_delivery_date", "type": "DATE", "description": "Requested delivery", "example": "2024-04-15"},
            {"name": "ship_to_dodaac", "type": "VARCHAR(6)", "description": "Delivery DoDAAC", "example": "W45G09"},
            {"name": "ship_to_name", "type": "VARCHAR(80)", "description": "Delivery location name", "example": "Anniston Army Depot"},
            {"name": "status", "type": "VARCHAR(20)", "description": "Status enum (DRAFT, SUBMITTED, APPROVED, SHIPPED, RECEIVED, CLOSED)", "example": "APPROVED"},
            {"name": "priority", "type": "INTEGER", "description": "Supply priority (1-15)", "example": "2"},
            {"name": "funding_code", "type": "VARCHAR(20)", "description": "Appropriation/fund cite", "example": "2142A000"},
            {"name": "approved_by", "type": "VARCHAR(50)", "description": "Approving official", "example": "col.richardson@army.mil"},
            {"name": "approved_date", "type": "DATE", "description": "Approval date", "example": "2024-01-10"},
            {"name": "created_at", "type": "TIMESTAMP WITH TIME ZONE", "description": "Record creation timestamp", "example": "2024-01-08T09:00:00Z"},
            {"name": "updated_at", "type": "TIMESTAMP WITH TIME ZONE", "description": "Last update timestamp", "example": "2024-01-10T15:45:00Z"},
        ],
    },
    "inventory": {
        "description": "Unified Inventory - Consolidated stock positions across all locations",
        "table_name": "inventory",
        "source_tables": ["GCSS-Army.MARA_SUPPLY", "LMP.WAREHOUSE_INVENTORY"],
        "fields": [
            {"name": "inventory_id", "type": "UUID", "description": "Unique inventory record ID", "example": "f6a7b8c9-d0e1-2345-fabc-456789012345"},
            {"name": "item_id", "type": "UUID", "description": "FK to supply_items", "example": "c3d4e5f6-a7b8-9012-cdef-123456789012"},
            {"name": "location_dodaac", "type": "VARCHAR(6)", "description": "Location DoDAAC", "example": "W45G09"},
            {"name": "location_name", "type": "VARCHAR(80)", "description": "Location description", "example": "Anniston Army Depot - Bldg 401"},
            {"name": "location_type", "type": "VARCHAR(20)", "description": "Type enum (DEPOT, UNIT_SSA, FIELD_SITE)", "example": "DEPOT"},
            {"name": "bin_location", "type": "VARCHAR(20)", "description": "Bin/shelf location", "example": "A-04-B-12"},
            {"name": "quantity_on_hand", "type": "DECIMAL(13,3)", "description": "Current on-hand qty", "example": "2450.000"},
            {"name": "quantity_reserved", "type": "DECIMAL(13,3)", "description": "Reserved quantity", "example": "500.000"},
            {"name": "quantity_available", "type": "DECIMAL(13,3)", "description": "Available quantity", "example": "1950.000"},
            {"name": "lot_number", "type": "VARCHAR(30)", "description": "Lot/batch number", "example": "LOT-2023-11-4108"},
            {"name": "condition_code", "type": "VARCHAR(2)", "description": "Condition code (A=Serviceable, etc.)", "example": "A"},
            {"name": "expiration_date", "type": "DATE", "description": "Expiration date (NULL=no expiry)", "example": "2025-11-30"},
            {"name": "unit_cost", "type": "DECIMAL(11,2)", "description": "Unit cost (USD)", "example": "47.50"},
            {"name": "total_value", "type": "DECIMAL(15,2)", "description": "Total position value", "example": "116375.00"},
            {"name": "last_count_date", "type": "DATE", "description": "Last physical inventory date", "example": "2023-12-15"},
            {"name": "last_transaction_date", "type": "DATE", "description": "Last receipt/issue date", "example": "2024-01-12"},
            {"name": "created_at", "type": "TIMESTAMP WITH TIME ZONE", "description": "Record creation timestamp", "example": "2024-01-01T00:00:00Z"},
            {"name": "updated_at", "type": "TIMESTAMP WITH TIME ZONE", "description": "Last update timestamp", "example": "2024-01-12T16:00:00Z"},
        ],
    },
    "shipments": {
        "description": "Unified Shipment Tracking - All materiel movements between locations",
        "table_name": "shipments",
        "source_tables": ["LMP.SHIPMENT_TRACKING"],
        "fields": [
            {"name": "shipment_id", "type": "UUID", "description": "Unique shipment identifier", "example": "a7b8c9d0-e1f2-3456-abcd-567890123456"},
            {"name": "legacy_system", "type": "VARCHAR(20)", "description": "Originating system", "example": "LMP"},
            {"name": "legacy_shipment_id", "type": "VARCHAR(20)", "description": "Original shipment ID", "example": "SHP-00891234"},
            {"name": "tcn", "type": "VARCHAR(20)", "description": "Transportation Control Number", "example": "W45G09-4108-0001"},
            {"name": "shipment_type", "type": "VARCHAR(20)", "description": "Type enum (SURFACE, AIR, SEALIFT, MULTIMODAL)", "example": "SURFACE"},
            {"name": "origin_dodaac", "type": "VARCHAR(6)", "description": "Origin DoDAAC", "example": "W45G09"},
            {"name": "origin_name", "type": "VARCHAR(80)", "description": "Origin location name", "example": "Anniston Army Depot"},
            {"name": "destination_dodaac", "type": "VARCHAR(6)", "description": "Destination DoDAAC", "example": "W45XAA"},
            {"name": "destination_name", "type": "VARCHAR(80)", "description": "Destination location name", "example": "2ABCT, 1AD - Fort Bliss"},
            {"name": "item_id", "type": "UUID", "description": "FK to supply_items", "example": "c3d4e5f6-a7b8-9012-cdef-123456789012"},
            {"name": "procurement_order_id", "type": "UUID", "description": "FK to procurement_orders (if applicable)", "example": "e5f6a7b8-c9d0-1234-efab-345678901234"},
            {"name": "quantity", "type": "DECIMAL(13,3)", "description": "Shipped quantity", "example": "100.000"},
            {"name": "weight_lbs", "type": "DECIMAL(11,2)", "description": "Total weight (lbs)", "example": "245.00"},
            {"name": "ship_date", "type": "DATE", "description": "Ship date", "example": "2024-01-10"},
            {"name": "estimated_arrival", "type": "DATE", "description": "Estimated arrival date", "example": "2024-01-17"},
            {"name": "actual_arrival", "type": "DATE", "description": "Actual arrival (NULL if in transit)", "example": None},
            {"name": "carrier", "type": "VARCHAR(50)", "description": "Carrier name", "example": "DLA Distribution"},
            {"name": "status", "type": "VARCHAR(20)", "description": "Status enum (PENDING, IN_TRANSIT, DELIVERED, RETURNED)", "example": "IN_TRANSIT"},
            {"name": "hazmat_class", "type": "VARCHAR(10)", "description": "Hazmat classification", "example": "NONE"},
            {"name": "created_at", "type": "TIMESTAMP WITH TIME ZONE", "description": "Record creation timestamp", "example": "2024-01-10T06:00:00Z"},
            {"name": "updated_at", "type": "TIMESTAMP WITH TIME ZONE", "description": "Last update timestamp", "example": "2024-01-12T14:30:00Z"},
        ],
    },
    "readiness_reports": {
        "description": "Unified Readiness Reporting - Equipment status rollup by unit and category",
        "table_name": "readiness_reports",
        "source_tables": ["GCSS-Army.UNIT_READINESS"],
        "fields": [
            {"name": "report_id", "type": "UUID", "description": "Unique report identifier", "example": "b8c9d0e1-f2a3-4567-bcde-678901234567"},
            {"name": "legacy_system", "type": "VARCHAR(20)", "description": "Originating system", "example": "GCSS_ARMY"},
            {"name": "legacy_report_id", "type": "VARCHAR(30)", "description": "Original report ID", "example": "USR-2024-0115-1AD"},
            {"name": "uic", "type": "VARCHAR(6)", "description": "Unit UIC", "example": "W45XAA"},
            {"name": "unit_name", "type": "VARCHAR(80)", "description": "Unit designation", "example": "2D ABCT, 1ST ARMORED DIVISION"},
            {"name": "report_date", "type": "DATE", "description": "Report date", "example": "2024-01-15"},
            {"name": "asset_category", "type": "VARCHAR(30)", "description": "Equipment category", "example": "TRACKED_VEHICLE"},
            {"name": "authorized_quantity", "type": "INTEGER", "description": "MTOE authorized qty", "example": "58"},
            {"name": "on_hand_quantity", "type": "INTEGER", "description": "On-hand quantity", "example": "56"},
            {"name": "fmc_quantity", "type": "INTEGER", "description": "Fully Mission Capable qty", "example": "48"},
            {"name": "pmc_quantity", "type": "INTEGER", "description": "Partially Mission Capable qty", "example": "5"},
            {"name": "nmc_quantity", "type": "INTEGER", "description": "Not Mission Capable qty", "example": "3"},
            {"name": "fmc_rate", "type": "DECIMAL(5,2)", "description": "FMC rate percentage", "example": "85.71"},
            {"name": "deadline_quantity", "type": "INTEGER", "description": "Deadline (awaiting parts) qty", "example": "2"},
            {"name": "commander_remarks", "type": "TEXT", "description": "Commander/NCO remarks", "example": "2x M1A2 awaiting powerpack; ESD 30JAN"},
            {"name": "created_at", "type": "TIMESTAMP WITH TIME ZONE", "description": "Record creation timestamp", "example": "2024-01-15T18:00:00Z"},
        ],
    },
}

# Dataset migration definitions - what appears in the dashboard
MIGRATION_DATASETS = [
    {
        "id": "equipment-assets",
        "name": "Equipment & Asset Records",
        "description": "Migrate equipment master records from GCSS-Army into the unified asset registry. Includes vehicles, weapons systems, C4ISR equipment, and all associated metadata.",
        "source_system": "GCSS-Army",
        "source_table": "EQUI_MASTER",
        "target_table": "assets",
        "record_count": 12847,
        "complexity": "HIGH",
        "estimated_duration": "45 min",
        "status": "NOT_STARTED",
    },
    {
        "id": "maintenance-orders",
        "name": "Maintenance Work Orders",
        "description": "Migrate maintenance work orders from GCSS-Army. Requires mapping SAP PM order types to unified status enums and linking to migrated asset records.",
        "source_system": "GCSS-Army",
        "source_table": "AUFK_WORKORDER",
        "target_table": "maintenance_orders",
        "record_count": 34521,
        "complexity": "HIGH",
        "estimated_duration": "60 min",
        "status": "NOT_STARTED",
    },
    {
        "id": "supply-catalog",
        "name": "Supply Catalog (Materiel Master)",
        "description": "Consolidate material master records from GCSS-Army supply data and LMP warehouse catalog into a unified supply items table. Requires deduplication by NSN.",
        "source_system": "GCSS-Army + LMP",
        "source_table": "MARA_SUPPLY + WAREHOUSE_INVENTORY",
        "target_table": "supply_items",
        "record_count": 89234,
        "complexity": "CRITICAL",
        "estimated_duration": "90 min",
        "status": "NOT_STARTED",
    },
    {
        "id": "vendor-master",
        "name": "Vendor/Supplier Registry",
        "description": "Migrate vendor master data from LMP into the unified vendor registry. Includes CAGE code validation and SAM.gov entity mapping.",
        "source_system": "LMP",
        "source_table": "VENDOR_MASTER",
        "target_table": "vendors",
        "record_count": 4312,
        "complexity": "MEDIUM",
        "estimated_duration": "30 min",
        "status": "NOT_STARTED",
    },
    {
        "id": "procurement",
        "name": "Procurement Orders",
        "description": "Migrate purchase orders and line items from LMP. Requires flattening PO header + line item structure and linking to migrated vendor records.",
        "source_system": "LMP",
        "source_table": "PURCHASE_ORDERS + PO_LINE_ITEMS",
        "target_table": "procurement_orders",
        "record_count": 15678,
        "complexity": "HIGH",
        "estimated_duration": "60 min",
        "status": "NOT_STARTED",
    },
    {
        "id": "inventory",
        "name": "Inventory Positions",
        "description": "Consolidate inventory from GCSS-Army unit-level stock and LMP depot-level warehouse positions into a unified inventory table.",
        "source_system": "GCSS-Army + LMP",
        "source_table": "MARA_SUPPLY + WAREHOUSE_INVENTORY",
        "target_table": "inventory",
        "record_count": 156789,
        "complexity": "CRITICAL",
        "estimated_duration": "120 min",
        "status": "NOT_STARTED",
    },
    {
        "id": "shipments",
        "name": "Shipment & Transportation Records",
        "description": "Migrate shipment tracking data from LMP. Map transportation control numbers and link to migrated procurement orders and supply items.",
        "source_system": "LMP",
        "source_table": "SHIPMENT_TRACKING",
        "target_table": "shipments",
        "record_count": 67432,
        "complexity": "MEDIUM",
        "estimated_duration": "45 min",
        "status": "NOT_STARTED",
    },
    {
        "id": "readiness",
        "name": "Unit Readiness Reports",
        "description": "Migrate unit readiness reporting data from GCSS-Army. Standardize equipment categories and link to migrated asset records for drill-down capability.",
        "source_system": "GCSS-Army",
        "source_table": "UNIT_READINESS",
        "target_table": "readiness_reports",
        "record_count": 8945,
        "complexity": "LOW",
        "estimated_duration": "20 min",
        "status": "NOT_STARTED",
    },
]
